const util = require("util");

const mrts = [
  "Ang Mo Kio",
  "Bartley",
  "Bayfront",
  "Aljunied",
  "Beauty World",
  "Bendemeer",
  "Bencoolen",
  "Bedok Reservoir",
  "Bishan",
  "Boon Keng",
  "Braddell",
  "Boon Lay",
  "Botanic Gardens",
  "Bras Basah",
  "Buangkok",
  "Bugis",
  "Bukit Gombak",
  "Bukit Batok",
  "Bukit Panjang",
  "Buona Vista",
  "Caldecott",
  "Canberra",
  "Cashew",
  "Changi Airport",
  "Chinatown",
  "Chinese Garden",
  "City Hall",
  "Choa Chu Kang",
  "Clarke Quay",
  "Clementi",
  "Dakota",
  "Commonwealth",
  "Dhoby Ghaut",
  "Dover",
  "Downtown",
  "Expo",
  "Esplanade",
  "Farrer Road",
  "Eunos",
  "Farrer Park",
  "Fort Canning",
  "Gul Circle",
  "Geylang Bahru",
  "Haw Par Villa",
  "HarbourFront",
  "Holland Village",
  "Hougang",
  "Hillview",
  "Joo Koon",
  "Jalan Besar",
  "Jurong East",
  "Kent Ridge",
  "Kaki Bukit",
  "Kallang",
  "Kembangan",
  "Khatib",
  "Kovan",
  "King Albert Park",
  "Kranji",
  "Labrador Park",
  "Lakeside",
  "Lavender",
  "MacPherson",
  "Lorong Chuan",
  "Little India",
  "Marina South Pier",
  "Marina Bay",
  "Marsiling",
  "Mountbatten",
  "Marymount",
  "Mattar",
  "Newton",
  "Nicoll Highway",
  "one-north",
  "Novena",
  "Orchard",
  "Outram Park",
  "Pasir Panjang",
  "Paya Lebar",
  "Pasir Ris",
  "Pioneer",
  "Potong Pasir",
  "Promenade",
  "Punggol",
  "Queenstown",
  "Raffles Place",
  "Redhill",
  "Rochor",
  "Sembawang",
  "Sengkang",
  "Serangoon",
  "Simei",
  "Sixth Avenue",
  "Somerset",
  "Stadium",
  "Stevens",
  "Tai Seng",
  "Tampines",
  "Tampines East",
  "Tampines West",
  "Telok Blangah",
  "Tanjong Pagar",
  "Tan Kah Kee",
  "Tanah Merah",
  "Telok Ayer",
  "Tiong Bahru",
  "Tuas Crescent",
  "Toa Payoh",
  "Tuas Link",
  "Tuas West Road",
  "Woodlands",
  "Bedok",
  "Woodlands North",
  "Bedok North",
  "Yew Tee",
  "Woodlands South",
  "Woodleigh",
  "Yishun",
  "Yio Chu Kang",
  "Upper Changi",
  "Ubi",
];

module.exports = mrts;
