const towns = [
  "Hougang",
  "Woodlands",
  "Sembawang",
  "Ang Mo Kio",
  "Yishun",
  "Pasir Ris",
  "Serangoon",
  "Bedok",
  "Tampines",
  "Bukit Batok",
  "Jurong East",
  "Choa Chu Kang",
  "Bukit Pangang",
  "Clementi",
  "Jurong West",
  "Bishan",
  "Central Area",
  "Bukit Timah",
  "Bukit Merah",
  "Tengah",
  "Punggol",
  "Kallang",
  "Queenstown",
  "Toa Payoh",
  "Marine Parade",
  "Whampoa",
  "Sengkang",
  "Geylang",
];

module.exports = towns;
